### ISSUE TITLE
"sodium.h" file not found

### ISSUE THREAD

**Issue by Julyyq** [shadowsocks/shadowsocks-iOS#100]
I saw [libsodium](https://github.com/jedisct1/libsodium) was added to this project at commit [add libsodium](https://github.com/shadowsocks/shadowsocks-iOS/commit/3a338e4d5faab85a211bf1d50393fd32c6772d6f), but there's no documentation for integrating this library. Can you add it? Thanks in advance.

**Comment by loadmemo** [comment]
same problem.
