### ISSUE TITLE
其实可以增加一下负载均衡的功能-》通过pac实现

### ISSUE THREAD

**Issue by qdore** [shadowsocks/shadowsocks-iOS#104]
可以指定多个服务器，在pac文件里面做负载均衡

**Comment by clowwindy** [comment]
I didn't get the idea but you can put your idea in code and send a pull request.

**Comment by xujun1986** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases/tag/2.5

Function Requirements ：）
