### ISSUE TITLE
一个似乎可行的 iOS 常驻后台方法

### ISSUE THREAD

**Issue by beidouchangxi** [shadowsocks/shadowsocks-iOS#105]
后台播放一段空白音频，让系统以为自己在播放音乐……这样就不会被干掉了。

作者要不要考虑考虑？

**Comment by clowwindy** [comment]
Waste of battery life and forbidden by the App Store.

**Comment by dingyaguang117** [comment]
费电这个应该是用户自己权衡，另外我看很多应用都是通过播放背景音乐实现常驻后台的，并且通过了审核。 我们的APP就通过审核了。
