### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by Rxywyn** [shadowsocks/shadowsocks-iOS#106]
hi, am new to this, recently shadowsocks stopped loading any page at all, even Google cant be loaded, are there settings I have to change? please help. thank you. :)

**Comment by Rxywyn** [comment]
I'm also on iOS, I forgot to mention that bit.

**Comment by clowwindy** [comment]
We can't reproduce the problem. Please provide more information.

**Comment by Rxywyn** [comment]
I'm currently running iOS 8.1.2, on jailbreak. I'm not sure what's wrong either, I used to be able to just open the app and use it, have not set up any servers or proxies within the app itself.

**Comment by Rxywyn** [comment]
when I type in a url, it's just a blank page. have tried to quit the app and restart it but it's still as it is.

**Comment by Rxywyn** [comment]
![](http://i.imgur.com/VQhyXTv.jpg)

just stays like that.

**Comment by clowwindy** [comment]
Check your server settings.

**Comment by Rxywyn** [comment]
may I know how or what they should look like? they're currently in public instead of custom.

**Comment by clowwindy** [comment]
Public servers are generally slow and are just provided as _hopefully helpful_, with no availability promise. You may try to set up your own server.
