### ISSUE TITLE
Other Apps can't use shadowsocks as proxy

### ISSUE THREAD

**Issue by wenjiehu** [shadowsocks/shadowsocks-iOS#108]
iPad 4, iOS 8.2, Shadowsocks 3

I have already set HTTP proxy to "Auto" and set the url to "http://127.0.0.1:8090/proxy.pac". But I still can't visit Facebook, Twitter and Youtube with Safari, Chrome or other Apps, while I can visit them on the embedded browser of ShadowSocks.

Somebody on http://groups.google.com/group/shadowsocks reported the same error.

It also crash when change proxy mode.

**Comment by clowwindy** [comment]
Will be fixed in the next release.

Expect about 2 weeks App Store review time.
