### ISSUE TITLE
Doesn't work for terminal tools (OS X)

### ISSUE THREAD

**Issue by canmor** [shadowsocks/shadowsocks-iOS#109]
Shadowsocks seams doesn't work for terminal tools. After the Shadowsocks was enabled, I can visit [https://www.google.com.hk](https://www.google.com.hk) in Safari, but can not `ping www.google.com.hk`. Other tools such as `lynx`, `wget` also doesn't work. Is there any extra setup need to be done?

**Comment by clowwindy** [comment]
For TCP-based tools you can use [proxychains](https://github.com/shadowsocks/shadowsocks/wiki/Using-Shadowsocks-with-Command-Line-Tools).

For IP level tools like ping, you need VPN.

**Comment by canmor** [comment]
Thank you for your help, I'd already found out a solution, might not the better one:
1. Use _privoxy_ to forward _http_ proxy to _socks5_ proxy.
   
   ```
   $ brew install privoxy
   ```
   
   Add these lines to `/usr/local/etc/privoxy/config`:
   
   ```
   listen-address [::1]:8118
   listen-address  127.0.0.1:8118
   forward-socks5 / localhost:1080 .
   ```
   
   > #### Note:
   > 1. There might be already a `listen-address 127.0.0.1:8118` line in the file, **do not** repeat it.
   > 2. `listen-address [::1]:8118` is for IPv6, it's **important** because it's requried for some tools (as I known: wget).
2. Add some scripts to your shell profile (for bash on OS X, it's `~/.bash_profile`) for helping enable/disable proxy:
   
   ```
   function set_proxy_on()
   {
       /usr/local/sbin/privoxy /usr/local/etc/privoxy/config
       export https_proxy='http://localhost:8118'
       export http_proxy='http://localhost:8118'
   }
   
   function set_proxy_off()
   {
       unset http_proxy
       unset https_proxy
       ps -A | grep sbin\/privoxy | grep -v grep | cut -d' ' -f2 | xargs kill -9
   }
   ```
   
   Reload profile:
   
   ```
   $ source ~/.bash_profile
   ```
3. Now, just run:
   
   ```
   $ set_proxy_on
   ```
   
   to turn on proxy. Run:
   
   ```
   $ set_proxy_off
   ```
   
   to turn off proxy.

**Comment by CoXier** [comment]
Hello everyone.😀

How can I get my local port? 

Thanks in advance.

**Comment by canmor** [comment]
@CoXier If local port means the SOCK5 service provided by Shadowsocks, it's on localhost:1080.

**Comment by dennisdebel** [comment]
This is not working anymore
