### ISSUE TITLE
global proxy still not work in version 3.0.1

### ISSUE THREAD

**Issue by 3dnow** [shadowsocks/shadowsocks-iOS#111]
The newest version 3.0.1 of shadowsocks for iOS claim it fixes global proxy problem, but it isn't.

I killed shadowsocks process and tried this multiple times, but global proxy function still not work on my iPhone6 , and the http service does not even exist on 8090 port.

OS version:8.1.3
System language: English
iPhone model : iPhone6 128GB

**Comment by clowwindy** [comment]
Can't reproduce your problem on iOS 8.2 with 3.0.1. The PAC file can be downloaded from http://127.0.0.1:8090/proxy.pac, and the proxy works well with Safari.

**Comment by 3dnow** [comment]
You may notice there are same report on App Store customer reviews of current version

**Comment by 3dnow** [comment]
How could I help you to address this issue? I think the problem is web server of shadowsocks doesn't work well.

**Comment by 3dnow** [comment]
The global proxy function work fine before I updated version 3.0. Maybe  there are some code related to web server/global proxy configuration changed incorrectly start from this version?

**Comment by clowwindy** [comment]
I can only verify it works with Safari on my devices and I don't know how to reproduce your problem. You may try to download the PAC file on your iPhone or from your computer to test if the HTTP server works.

The report for global proxy issue is not just in this version. Most of the apps like Chrome and Twitter which use their own SPDY protocols don't support system proxy settings. The users can't tell the difference and come to report on the App Store.

**Comment by 3dnow** [comment]
I already tried to download the pac file.Safari and good reader said the server can not connected , then I used some net tools to scan port on 127.0.0.1 ,it also said the port 8090 is not open.that's why I said the web server is not exist.

**Comment by 3dnow** [comment]
I tried remove and reinstall shadowsocks,reboot phone,it still not work

I tried on my friend's iPhone 6(16GB Model), Global proxy also not work on her iPhone.

On her phone there are 2.4 version shadowsocks installed already, and I tried to download pac file use safari it's works fine. 
Then I update shadowsocks to newest version, suddenly the pac file couldn't been download anymore.

**Comment by 3dnow** [comment]
btw,the another iPhone6 which I tested uses iOS 8.1.3.
Then I tested on other iPhone5s with clean environment (just wiped few days ago) , it uses iOS8.2 and global proxy also not work on it + Safari couldn't download pac file.
I also tried turn off wifi and use 4G/3G networks , change another wifi ... 8090 port still can not been reach.

So I think it maybe related to app 's web server functional itself and seems a very common problem.
Maybe you can use it on you phone because you have some special configuration on your phone?did you try tested on other clean phone ?

**Comment by clowwindy** [comment]
Reinstalled again and finally found the problem. It's a timing and cache related problem.

Normally an app team should have some QA people to test all the features before submission to App Store. But this is a free and personal project and I'm on myself. So, I'll test important features that I use everyday, upload and let the users to test the rest.

**Comment by 3dnow** [comment]
So will you fix this issue next version? Is there any workaround can help me mitigate this issue and use this function as before ? since you said it's a timing/caching related issue so maybe there will be some way

**Comment by 3dnow** [comment]
And I suggest you open a donation so people who like this app can help you impove it's quality . At least you can find some QA to test features or find issues for you.

**Comment by clowwindy** [comment]
It's a bit tricky and I can't explain how the PAC was cached previously on my device. I think the best is to wait for Apple to review the new version.

Thanks for your suggestion but donation won't help the situation.

**Comment by clowwindy** [comment]
3.0.2 was rejected by Apple. I guess we need more time.

**Comment by qgewfg** [comment]
Hi, clowwindy, has the source code of shadowsocks for iOS (v3.0.1) pushed into this repo or where else? I compiled the newest code of this repo for non-jailbroken iOS(v 8.2) to achieve global proxy, but it works on iOS 7 and doesn't work on iOS 8.

**Comment by clowwindy** [comment]
It seems that Apple will be reviewing this app forever.

**Comment by Willian-Zhang** [comment]
is it still under revision @clowwindy ?

**Comment by clowwindy** [comment]
Unfortunately yes.

**Comment by Willian-Zhang** [comment]
it's more likely they have somehow missed the app, ithink. 
ref# http://appreviewtimes.com/ios/distribution-chart

**Comment by clowwindy** [comment]
Just submitted a new binary.

**Comment by clowwindy** [comment]
Finally it's approved.

**Comment by tianhaopx** [comment]
Global proxy still not works in version 3.0.2. Tested on iPhone 5s, iPhone 6, iOS 8.3

**Comment by clowwindy** [comment]
1. Fill http://127.0.0.1:8090/proxy.pac into Wi-Fi HTTP Proxy Auto
2. Open Safari open Google search my ip
3. Shows proxy IP

**Comment by Yucheng-Ren** [comment]
IOS 9.3.1 Shadowsock 3.0.2 doesn't work in app.

**Comment by ourdark** [comment]
same issue,Shadowcocks not working in IOS 9.3.1
