### ISSUE TITLE
user-rule.txt 用户规则设置无效

### ISSUE THREAD

**Issue by heywin** [shadowsocks/shadowsocks-iOS#116]
OSX 10.10.2，用户规则无法设置。
我使用的是自动代理模式，由于github在我的网络环境访问不稳定，所以想把它加入用户规则，但是按照 https://github.com/JinnLynn/genpac/blob/master/genpac/res/user-rules-sample.txt
配置无效。

我把http://www.ip138.com和http://whatismyipaddress.com/ip-lookup添加到用户规则发现无效。

**Comment by minosss** [comment]
要重新更新pac~

**Comment by heywin** [comment]
果然可以~~~ 谢谢

没看到官方有此说明，望补上。

毕竟现在国内网络环境复杂，单靠一个GFWList不一定可以满足广大翻墙人民的需要。。。

**Comment by huhuang03** [comment]
请问我在哪里可以找得到use-rule.txt文件呢。我用的是shadowsocks MAC客户端

**Comment by zwpaper** [comment]
点任务栏的 Shadowsocks 图标，下面有 Edit User Rule for GFWList，点击就自动打开 user-rule.txt 所在目录。

**Comment by clowwindy** [comment]
官方是什么……

**Comment by wujun4code** [comment]
快被楼上萌爆了……哈哈哈哈……官方是什么……哈哈哈

**Comment by heywin** [comment]
你不就是官方么。。。。。。

**Comment by callzhang** [comment]
请问如何更新pac？还有，官方说明在哪里？

**Comment by xxlyu-2046** [comment]
> 要重新更新pac~

修改了user-rule.txt，怎么重新更新pac呢？

**Comment by xxlyu-2046** [comment]
> > 要重新更新pac~
> 
> 修改了user-rule.txt，怎么重新更新pac呢？

已解决，点击从gfwlist更新pac，会吧user-rule.txt的内容更新到pac中，如果连不上服务器，设为全局模式

**Comment by xxlyu-2046** [comment]
> 请问如何更新pac？还有，官方说明在哪里？

参考我上面的评论
