### ISSUE TITLE
无法使用，Log里一直提示这个

### ISSUE THREAD

**Issue by victorjiang-zz** [shadowsocks/shadowsocks-iOS#117]
![image](https://cloud.githubusercontent.com/assets/5085769/7387714/003a7b9c-ee92-11e4-9491-1462274c5bac.png)

**Comment by amdth** [comment]
我也有一样的问题，我是刚装的系统啊！

**Comment by clowwindy** [comment]
这个日志是正常的。使用相关问题请去论坛提问。

**Comment by amdth** [comment]
能够得到你的回复真是太好了，感谢你做的这些事情！
        不知道我应该从哪些方面来排除问题 我确定我的服务器填写的正确，客户端也经过了md5校验，电脑又不知道怎样来排除问题，多谢开发者！

发自我的 iPhone
