### ISSUE TITLE
[Feature][Mac]设置代理服务器允许局域网的其他设备共享使用

### ISSUE THREAD

**Issue by doskoi** [shadowsocks/shadowsocks-iOS#119]
目前Mac客户端只支持运行的机器使用，并且只有浏览器可以使用，其他程序不行。
可否让Mac客户端像路由器里运行的那样，让本机全局（可以gfwlist或china dns等方法）使用SS，并且能作为局域网其他机器的代理。

**Comment by clowwindy** [comment]
OS X 的内核没有提供这样的功能。

**Comment by laplacelove** [comment]
http://thepast.me/post/155105327
使用Privoxy间接实现这个功能。
我找了好久，终于发现了这个解决办法，太赞了。

**Comment by tbphp** [comment]
谁说mac版本不支持的？
ss偏好设置->HTTP->HTTP代理监听地址->修改为0.0.0.0
完成

**Comment by awper361** [comment]
@tbphp 非常感谢！

**Comment by xhacker5000** [comment]
@tbphp 正解

**Comment by SunJenry** [comment]
@tbphp That works!

**Comment by ghost** [comment]
> 谁说mac版本不支持的？
> ss偏好设置->HTTP->HTTP代理监听地址->修改为0.0.0.0
> 完成

求问原理是什么？

**Comment by luckKlaus** [comment]
6666666

**Comment by txperl** [comment]
@tbphp tql!

**Comment by fengjx** [comment]
> > 谁说mac版本不支持的？
> > ss偏好设置->HTTP->HTTP代理监听地址->修改为0.0.0.0
> > 完成
> 
> 求问原理是什么？

原理是监听的ip默认是127.0.0.1这个只能本机访问，改成0.0.0.0就是不限制网段，也可以改成192.168.1.100(假如你的局域网ip是这个的话)，那么就是限制192.168.1.xxx这个网段能访问。属于计算机网络底层的概念

**Comment by wuyqcode** [comment]
@tbphp感谢

**Comment by nicowu07** [comment]
请问这样设置之后好像共享热点仍然没有走ss？我用kindle连接热点ip仍然是国内的，是否只能是连接的终端设置proxy后才能走mac的ss呢？

**Comment by 7u** [comment]
@tbphp 只说对了一半，监听地址改成全网段确实可以代理到其他设备，但是也仅限于http协议，socks5协议还是不通。目前暂未找到解决方法。
