### ISSUE TITLE
This application sends emails to Mozillla

### ISSUE THREAD

**Issue by st3fan** [shadowsocks/shadowsocks-iOS#120]
Hi, one of the _Firefox for iOS_ developers here. We feel flattered that you used our code for this iOS application. But, you really need to remove the feedback functionality that sends an email to `ios-feedback at mozilla.com`.

We get dozens of (empty) emails from your users, which is annoying.

Also, _this compromises the anonymity of your users_ because the email is sent using the users' configured email account.

Please fix this. The code for this is in AppDelegate.swift. Just remove the code that sends the feedback emails, or replace the email address with your own support email address.

**Comment by clowwindy** [comment]
We apologize for the problem. We've noticed the problem and submitted a fix to the App Store. However this version has been in In Review status for more than a month. We'll try to resubmit the version to see if Apple will approve sooner.

**Comment by clowwindy** [comment]
Finally it's approved.
