### ISSUE TITLE
OSX版偶发的代理失效问题

### ISSUE THREAD

**Issue by wdhwg001** [shadowsocks/shadowsocks-iOS#122]
RT. 问题表现为部分网页一直白屏+卡进度条，需要点击关闭代理，然后点击开启代理，之后重新在地址栏点一下并按回车，网页才能正常打开。
尚不清楚问题的出现原因，也不知道如何确定的重现问题…姑且提一下Issue，等待更多反馈吧。

**Comment by wdhwg001** [comment]
15/6/3 下午2:48:34.522 networkd[185]: -[NETProxyLookup pacLookupComplete:proxies:error:] PAC evaluation error: Error Domain=NSPOSIXErrorDomain Code=61 "The operation couldn’t be completed. Connection refused"
这样的一模一样的消息填满了Log，直至关闭PAC并重新打开才恢复正常。
在填满的期间，代理是无法正常工作的。

**Comment by clowwindy** [comment]
https://www.v2ex.com/t/174191
