### ISSUE TITLE
safari invalid in OS X 10.11

### ISSUE THREAD

**Issue by pupboss** [shadowsocks/shadowsocks-iOS#125]
Hi, there

chrome works well, but safari can't.

I put the proxy.pac on my web server, close the PAC, and do like this:

![](http://ww4.sinaimg.cn/large/85c68139jw1esxx9y3qhlj20i30e2q4q.jpg)

It still don't work in safari.

Tks

**Comment by yzlnew** [comment]
同样的问题

**Comment by clowwindy** [comment]
Please report PAC problem to Apple.
