### ISSUE TITLE
Mac OS X EL Capitan DP1下无法翻墙

### ISSUE THREAD

**Issue by sparketainer** [shadowsocks/shadowsocks-iOS#127]
RT,程序可以打开，但是无法翻墙，账号密码IP都正确

**Comment by clowwindy** [comment]
苹果新版网络模块的 bug，之前 10.10.3 beta 上同样的问题，正式版里又退回老版了。
https://www.v2ex.com/t/197108?p=1

另外是否方便共享个 EL Capitan 的系统文件给我呢？
`/System/Library/Frameworks/NetworkExtension.framework` 下 `resources` 里的 `NEProviderTargetTemplates.pkg` 文件，大概 7MB.

**Comment by pzgz** [comment]
@clowwindy 
Here it's:  https://app.box.com/s/f0ao7yjn5cyh9wzuno7o4mo0f8o0jmx9

**Comment by sparketainer** [comment]
我发你twitter私信了

**Comment by clowwindy** [comment]
收到，多谢

**Comment by Mattosx** [comment]
这个问题是否 能修复阿?目测是Safari 不支持pac 和全局代理.chrome一切完好.

**Comment by clowwindy** [comment]
@regeditms 看一下一楼再回复难么？

**Comment by yyang** [comment]
谢谢 @clowwindy 。另外说明一下，DP2已经修复此bug。仍然遇到类似问题的小伙伴请更新至DP2。

**Comment by 731704267** [comment]
我安装了xcode7 beta 4  为什么没有NEProviderTargetTemplates.pkg 文件呢？ 谁可以发我一份吗

**Comment by 731704267** [comment]
@sparketainer 你好，可以发我一份NEProviderTargetTemplates.pkg文件吗

**Comment by daheli** [comment]
@731704267

NEProviderTargetTemplates.pkg

http://daheli.qiniudn.com/NEProviderTargetTemplates.pkg
