### ISSUE TITLE
安全漏洞：允许任意用户以 root 身份更改网络设置

### ISSUE THREAD

**Issue by V01dZer0** [shadowsocks/shadowsocks-iOS#128]
Mac 版安全漏洞：
任意用户登录到主机后，可以执行"/Library/Application Support/ShadowsocksX/shadowsocks_sysconf mode"来更改本机网络设置。
而此网络设置影响到主机上的全部登录用户。

建议将shadowsocks_sysconf放到安装 ShadowsocksX 的用户的 $HOME/Library/Containers/bundle_id_of_ ShadowsocksX下

**Comment by clowwindy** [comment]
If you have multiple users on your Mac and you don't want others to control Shadowsocks, just don't use it.
