### ISSUE TITLE
Mac OS Yosemite 10.10.3 突然无法翻墙

### ISSUE THREAD

**Issue by Neway6655** [shadowsocks/shadowsocks-iOS#129]
RT, 从今天(6.16)下午开始，突然就不能翻墙了,有遇到一样问题的同学么？

**Comment by viquu** [comment]
我是刚安装，发现不能用，日志里面看到日志：
···
15/6/21 下午8:51:13.237 ShadowsocksX[17590]: run shadowsocks helper: /Library/Application Support/ShadowsocksX/shadowsocks_sysconf
15/6/21 下午8:51:13.298 ShadowsocksX[17590]: pac proxy set to auto
15/6/21 下午8:51:13.304 configd[47]: network changed: v4(en0:192.168.99.193) DNS Proxy! SMB
15/6/21 下午8:51:26.908 ShadowsocksX[17590]: Connecting autoproxy-gfwlist.googlecode.com
15/6/21 下午8:51:47.013 ShadowsocksX[17590]: CFNetwork SSLHandshake failed (-9806)
15/6/21 下午8:51:47.105 ShadowsocksX[17590]: Connecting autoproxy-gfwlist.googlecode.com
15/6/21 下午8:52:07.210 ShadowsocksX[17590]: CFNetwork SSLHandshake failed (-9806)
15/6/21 下午8:52:07.299 ShadowsocksX[17590]: Connecting autoproxy-gfwlist.googlecode.com
15/6/21 下午8:52:08.480 ShadowsocksX[17590]: terminating
15/6/21 下午8:52:08.481 ShadowsocksX[17590]: run shadowsocks helper: /Library/Application Support/ShadowsocksX/shadowsocks_sysconf
15/6/21 下午8:52:08.552 ShadowsocksX[17590]: pac proxy set to off
···

**Comment by jasoncfpl** [comment]
怎么解决
