### ISSUE TITLE
8090端口可以被外部访问

### ISSUE THREAD

**Issue by vietor** [shadowsocks/shadowsocks-iOS#130]
此端口只被本机使用的情况下，应该绑定本机地址，而不能被外部访问。当前通过nmap能够扫描到此端口。

**Comment by CaledoniaProject** [comment]
同问，这个东西是干啥的啊

**Comment by xJogger** [comment]
此问题已有人提过，参见：https://github.com/shadowsocks/shadowsocks-iOS/issues/68
