### ISSUE TITLE
OSX更新到10.10.4后出现的崩溃问题

### ISSUE THREAD

**Issue by EncodeX** [shadowsocks/shadowsocks-iOS#138]
查看崩溃报告的信息是下面这一条，半天内已经发生了十多次。
Dispatch queue: com.apple.root.default-qos

![b5f6895d-15c6-4198-a0b6-3f200c558355](https://cloud.githubusercontent.com/assets/3592089/8497480/15d77e22-21b0-11e5-91ea-902101e1f670.png)

**Comment by clowwindy** [comment]
https://www.v2ex.com/t/202961#reply19
