### ISSUE TITLE
新版OSX存在不能切换服务器的BUG

### ISSUE THREAD

**Issue by zhaochunqi** [shadowsocks/shadowsocks-iOS#142]
新版本的shadowsocks在切换服务器的时候不会改变，只有重启shadowsocks才会切换过来。

**Comment by clowwindy** [comment]
https://github.com/shadowsocks/shadowsocks-iOS/wiki/Shadowsocks-for-OSX-Help

> You may need to restart Chrome after you choose another server.

**Comment by zhaochunqi** [comment]
测试过很多遍了，之前版本不存在问题。
而且，切换pac和global也需要重启shadowsocks。
不认为是chrome问题。

**Comment by clowwindy** [comment]
There is no new version since March.

**Comment by zhaochunqi** [comment]
就是3月的版本，添加了自动获取GFW list功能的版本。
我也不清楚，为什么这么久没人提过这个问题。
我用time machine恢复到之前版本了，正常。

**Comment by clowwindy** [comment]
1. You do have to restart Chrome or close or flush all sockets after switching servers. Else existing web pages won't reconnect.
2. For PAC and global switching, it works fine for me.

**Comment by zhaochunqi** [comment]
I know that , sorry for the disturb. I guess it's just my problem.
