### ISSUE TITLE
C大，有时间的话麻烦将OS X版和Win版功能同步。

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-iOS#148]
@clowwindy 辛苦了

**Comment by clowwindy** [comment]
项目太多了，暂时没有精力这么快同步
- Shadowsocks
- Shadowsocks-iOS
- Shadowsocks-Windows
- Shadowsocks-OSX
- ChinaDNS
- ShadowVPN
- ShadowVPN-iOS
- ShadowVPN-Android
- gfwlist2pac
