### ISSUE TITLE
Why not just startup at login

### ISSUE THREAD

**Issue by superlbr** [shadowsocks/shadowsocks-iOS#153]

**Comment by tobielf** [comment]
@superlbr 
Startup at login requires root privilege. You can achieve this by follow steps on OSX:
"System Preferences"-"Users & Groups"- Select your account and then switch to the "Login Items" tab.
Click the "+" icon, located to the "Application" folder, find out "Shadowsocks", click "OK".
Done, I hope you enjoy with it.

**Comment by superlbr** [comment]
@tobielf thank you,it works.
