### ISSUE TITLE
二维码用途

### ISSUE THREAD

**Issue by HelloWilliam** [shadowsocks/shadowsocks-iOS#158]
二维码用途？？不懂

**Comment by Keystion** [comment]
用途：快速分享给别人；

生成二维码 `->` 发给朋友 `->`  朋友「从屏幕扫描二维码」`->`  打开`shadowsocks-iOS` 就可以使用了

> 整个过程中朋友不需要填写服务器、端口、用户名及密码，因为二维码中都带上了这些信息，「从屏幕扫描二维码」会获取这些信息然后自动填充保存

![image](https://cloud.githubusercontent.com/assets/2408287/10596580/48e2f4e6-7718-11e5-86b1-b10e0e73c163.png)

**Comment by albertcsg** [comment]
嗯 对的。二维码上添加了服务器之类的信息。
