### ISSUE TITLE
用户规则google无效

### ISSUE THREAD

**Issue by zmofei** [shadowsocks/shadowsocks-iOS#159]
自动代理模式下更新的gfwlist 没有google

于是在用户规则中填写如下google规则任然不能访问google

```
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet

||www.google.com
||google.com
```

请问如何在用户规则中添加某个域名？
![image](https://cloud.githubusercontent.com/assets/3351337/10634312/848fa0b4-7823-11e5-83f3-0596f700487d.png)

**Comment by Migflyway** [comment]
不是这里写吧

**Comment by celerysoft** [comment]
在这里添加自定义规则之后，需要重新执行一遍**从 GFWList 更新 PAC**，`user-rule.txt`的作用是在每次用户从 GFWList 更新 PAC时，将自定义规则写到`gfwlist.js`中，实际上，是通过`gfwlist.js`来控制自定义规则的。
