### ISSUE TITLE
OSX: Dropbox 无法同步

### ISSUE THREAD

**Issue by franklinzhang** [shadowsocks/shadowsocks-iOS#186]
已经设定dropbox的代理服务器：

> 手动
> socks5
> 127.0.0.1:1080

但是没法同步了，之前一段时间是好的。

**Comment by oscarqht** [comment]
這是Dropbox或者你網絡的問題，跟SS沒關係吧

**Comment by franklinzhang** [comment]
问题解决了，重启dropbox就好了。
