### ISSUE TITLE
facebook app上不去。

### ISSUE THREAD

**Issue by EkkoG** [shadowsocks/shadowsocks-iOS#20]
twitter google+ 网页facebook都是可以的，唯独facebook上不去，我试了把手机重新刷机，只装facebook然后越狱装ss，也是不行的。

**Comment by linmax1983** [comment]
操蛋。。。。。

**Comment by zeroxia** [comment]
现在Twitter是不是也用上SPDY了？ Global模式的shadowsocks也无法用于Twitter app了。
