### ISSUE TITLE
群主能不能发给我一份啊。

### ISSUE THREAD

**Issue by ilovebamboo** [shadowsocks/shadowsocks-iOS#200]
我想要编译一下

**Comment by ilovebamboo** [comment]
970665177@QQ.COM

**Comment by bluceshang** [comment]
为什么现在完全连接不上了呀，连网站登录页面也进不了，代理完全就废了，是不是要更新gfwlist.js文件，谁能发我一分吗？1323506213@qq.com

**Comment by fengzipei** [comment]
可以给我一分吗？谢谢～fengzipei3@gmail.com

**Comment by ilovebamboo** [comment]
可以啊 你自己下啊 我主页上有

**Comment by lovelykids** [comment]
有编译好的大神么

**Comment by qiuyuzhou** [comment]
@lovelykids 这里不维护了
看这里 https://github.com/shadowsocks/ShadowsocksX-NG
