### ISSUE TITLE
Why can't support FireFox?

### ISSUE THREAD

**Issue by TommyTC** [shadowsocks/shadowsocks-iOS#204]
程序棒棒的，非常方便！！
为什么FireFox不能正常使用的，即使我尝试了几款Proxy插件，都选择了“System Proxy”选项，依然不行。我对Shadowsocks不太熟悉。
是在设计时没有根本就没有考虑FireFox，还是我没有设置正确呢？
望各位作者或者各位大大能告之其正确的使用姿势。🙏

**Comment by aieu** [comment]
貌似是firefox的问题
直接firefox socket是可以的，但是，pac中socket就不行了....

**Comment by stiffyfoto** [comment]
Firefox安装FoxyProxy扩展，为全部URL使用“默认”，然后把“默认”设为“使用系统代理设置”，就可以了
