### ISSUE TITLE
不能更新 PAC 文件

### ISSUE THREAD

**Issue by snakezzl** [shadowsocks/shadowsocks-iOS#212]
MAC  下点击“从 GFWList 更新 PAC”，提示“404”错误，请问怎么解决呢？

**Comment by Ryan-song** [comment]
提示“Request failed ： not found（404）”, 查看日志显示`Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fca35955dd0> { URL: https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt } { status code: 404, headers {
    "Content-Length" = 1582;
    "Content-Type" = "text/html; charset=UTF-8";
    Date = "Fri, 13 May 2016 02:43:57 GMT";
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"34,33,32,31,30,29,28,27,26,25\"";
    "alternate-protocol" = "443:quic";
} }, NSErrorFailingURLKey=https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt, com.alamofire.serialization.response.error.data=<3c21444f 43545950…………`。5月12日就出现了报错。

**Comment by charles0126dev** [comment]
遇到同样的问题.

**Comment by cicku** [comment]
Please manually update the gfwlist URL to the latest location:

`https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt`

Thanks.

**Comment by laona** [comment]
请问是在哪里更新gfwlist的URL呢？

**Comment by ghost** [comment]
如何取消收到通知

**Comment by nantingshi** [comment]
我的也不能更新了，求解

**Comment by nyankosama** [comment]
how to update gfwlist url??

**Comment by snowleopardw** [comment]
[gfwlist.zip](https://github.com/shadowsocks/shadowsocks-iOS/files/265194/gfwlist.zip)

**Comment by zld** [comment]
@laona 看下ShadowsocksX代码，是在代码中写死的。如果不改程序的话，直接把`gfwlist.js`下载下来替换原来的，再把自己的`user-rule.txt`里的设置按加上引号和逗号append到`gfwlist.js`中，重启ShadowsocksX就行了。

**Comment by laona** [comment]
@snowleopardw thks!

**Comment by laona** [comment]
@zld 谢谢，请问最新的gfwlist.js以后应该到哪里去下载呢？我刚才下了楼上那位兄弟的压缩包。

**Comment by zld** [comment]
@laona  https://github.com/gfwlist/gfwlist

**Comment by VincentSit** [comment]
刚刚也发现这个了问题，懒得编译 ShadowsocksX 了，我刚写了个脚本来更新 PAC，分享给大家使用。只在 OS X 上测试过。

https://gist.github.com/VincentSit/b5b112d273513f153caf23a9da112b3a

**Comment by snowleopardw** [comment]
sudo easy_install pip
sudo pip install gfwlist2pac

**Comment by laona** [comment]
@VincentSit  很好用，谢谢
sudo easy_install pip
sudo pip install gfwlist2pac
sudo update_gfwlist.sh

**Comment by laona** [comment]
@zld 谢谢！

**Comment by Sunjinwei** [comment]
@VincentSit 不行啊，还是404

**Comment by VincentSit** [comment]
@Sunjinwei 哪出现的 404?

**Comment by Sunjinwei** [comment]
@VincentSit 点击从GFWlist更新pac文件后。

**Comment by VincentSit** [comment]
@Sunjinwei 这个脚本并不是修复那个按钮，而是实现了那个按钮的功能。运行这个脚本已经更新了 PAC 了，你不需要再点击那个按钮了。

**Comment by Sunjinwei** [comment]
@VincentSit 也就是我自定义的用户规则生效了吗？

**Comment by VincentSit** [comment]
@Sunjinwei 是的。可以打开 `gfwlist.js` 搜索一下。

或者执行  
`grep -Fq $(awk '/./{line=$0} END{print line}' ~/.ShadowsocksX/user-rule.txt) ~/.ShadowsocksX/gfwlist.js ; echo $?`

如果输出 `0` 说明你的用户规则已经包含在 `gfwlist.js` 中了。

**Comment by Sunjinwei** [comment]
@VincentSit 非常感谢！

**Comment by S4MUEL-404** [comment]
非常感谢！

**Comment by snakezzl** [comment]
@VincentSit 谢谢～～～

**Comment by zhibocon** [comment]
手动下载https://github.com/gfwlist/gfwlist 得到的是 gfwlist.txt 怎么转换成gfwlist.js 呢？

**Comment by zld** [comment]
@bimulinsen 看楼上脚本

**Comment by Teraflopst** [comment]
已解决。感谢 @RobertYan 提供的编译版本。
https://github.com/RobertYan/ShadowsocksX/releases
提示：如程序不能运行，需要安装 libsodium 库。

**Comment by kchen0x** [comment]
@onestark 说的方法有效。@RobertYan 提供的编译版本可用，运行不了的使用

```
brew install libsodium
```

安装一下 `libsodium` 库，没有 `brew` 的请自行Google安装 home-brew。

**Comment by Sunjinwei** [comment]
@onestark 下载包404了，急求一份谢谢，hi.sunjinwei@gmail.com

**Comment by patrickpeng2091** [comment]
@RobertYan  @quentin-chen  
https://github.com/RobertYan/ShadowsocksX/releases/download/2.6.4/ShadowsocksX.2.6.4.zip
链接换了吗，  404

**Comment by patrickpeng2091** [comment]
https://github.com/RobertYan/ShadowsocksX/releases/   发现一个2.6.5

**Comment by patrickpeng2091** [comment]
https://github.com/RobertYan/ShadowsocksX/releases/download/2.6.5/Shadowsocks-2.6.5.dmg

**Comment by Teraflopst** [comment]
@Sunjinwei https://github.com/RobertYan/ShadowsocksX/releases

**Comment by xj90512** [comment]
@patrick4u 链接失效了，能否提供一下安装包？

**Comment by doem97** [comment]
我是小白。。。我看不懂诶    是现在终端里输入 
sudo easy_install pip
sudo pip install gfwlist2pac
brew install libsodium
然后把大神的代码输进终端是吗！

**Comment by doem97** [comment]
还有那个txt怎么转化成js呐~

**Comment by Sunjinwei** [comment]
@onestark 谢谢！

**Comment by Sunjinwei** [comment]
@onestark 怎么是个压缩包呀？不会用呢。

**Comment by Sunjinwei** [comment]
@patrick4u 对的呢，链接失效了。同求

**Comment by Teraflopst** [comment]
@Sunjinwei 现在人家只放出源码了，没有提供编译好的下载，你自己编译吧。

**Comment by Sunjinwei** [comment]
@onestark 我不知道肿么编译，能告诉下我肿么编译不？

**Comment by Teraflopst** [comment]
@Sunjinwei Xcode

**Comment by Sunjinwei** [comment]
@onestark 我有Xcode 不知如何操作呢。

**Comment by Teraflopst** [comment]
@Sunjinwei http://pan.baidu.com/s/1c2BeaVu

**Comment by Sunjinwei** [comment]
@onestark 非常感谢！

**Comment by theewind** [comment]
非常感谢，已解决。

**Comment by lazze** [comment]
@VincentSit 有个./update_gfwlist.sh: line 59: /usr/local/bin/gfwlist2pac: No such file or directory

这个报错，不过最后提示了 Updated. 这是成功了吗 -。-

**Comment by VincentSit** [comment]
@lazze 应该是没有成功，没有成功安装 `gfwlist2pac`，建议你安装楼上仁兄打包好的安装包，比用脚本强。我已经转战 surge 了。。。

**Comment by lazze** [comment]
@VincentSit 恩 的确是没安装成功  user-rule.txt这个文件生成了，不过里面没内容 

你说的是 https://github.com/RobertYan/ShadowsocksX/releases 这个吗 -。-

**Comment by VincentSit** [comment]
@lazze 我看了下提交历史，应该是这个，我没有下载过，你直接去下载安装试用就行了。

**Comment by lazze** [comment]
@VincentSit 恩恩，就是不是原生的也不管乱用 -。-

**Comment by neochne** [comment]
![image](https://cloud.githubusercontent.com/assets/7844207/20512183/b7d9c944-b0b8-11e6-841a-faab170cc8ff.png)
更新PAC 404啊！手动下载下来的gfwlist是加过密的啊！怎么搞啊！

**Comment by dreday966** [comment]
修复起来啊，这么多人使用这个软件
