### ISSUE TITLE
request failed:not found (404)

### ISSUE THREAD

**Issue by doem97** [shadowsocks/shadowsocks-iOS#218]
I updated my pac, but it warned me that. I searched on the github and it seems like that the website of GFWlist has changed. I don't know how to use linux and don't know what to do to solve the problem. Can anyone tell me what to do in a clear way I can understand?

**Comment by doem97** [comment]
I'm using OS X

**Comment by doem97** [comment]
我是小白。。。我看不懂诶 是现在终端里输入 
sudo easy_install pip
sudo pip install gfwlist2pac
brew install libsodium
然后把VincentSit大神的代码输进终端是吗

**Comment by snowleopardw** [comment]
https://www.dropbox.com/s/b4lmz1lq1hy1aep/Shadowsocks-2.6.5.dmg?dl=0

**Comment by kyosold** [comment]
@snowleopardw 下不下来

**Comment by ghost** [comment]
这个问题是由于托管在googlecode的PAC文件失效了。

```
https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt

文件迁移到了github:
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

```

见 #216 
希望能有人改一下源码重新打个包

**Comment by yohn89** [comment]
#216

**Comment by snowleopardw** [comment]
https://github.com/RobertYan/ShadowsocksX/releases/download/2.6.5/ShadowsocksX-2.6.5.dmg

**Comment by snowleopardw** [comment]
@yohn89 @doem97 https://github.com/RobertYan/ShadowsocksX/releases/download/2.6.5/ShadowsocksX-2.6.5.dmg

**Comment by zcracker** [comment]
能不能增加t Onetime Authentication啊

**Comment by snowrzy** [comment]
@snowleopardw 成功了，感谢

**Comment by doem97** [comment]
> @yohn89 @doem97 https://github.com/RobertYan/ShadowsocksX/releases/download/2.6.5/ShadowsocksX-2.6.5.dmg

Thanks so much. ;D Though after many years, I am a "code explorer" now. 

Appreciate for pioneers bridge the young boy with the world. That totally changed me.
