### ISSUE TITLE
hope to support manual mode(neither auto proxy nor global proxy)

### ISSUE THREAD

**Issue by warmonipa** [shadowsocks/shadowsocks-iOS#219]

**Comment by ethan0w** [comment]
u my click the 2nd menu to turn off Shadowsocks, the proxy server is still running. Then you can manually set the proxy of your browser or OS.  Rember to choose `SOCKS proxy` and address is `127.0.0.1` and port is `1080`, without password.

**Comment by warmonipa** [comment]
thanks, but ain't obvious
