### ISSUE TITLE
"Could not bind" 日志里一直显示这个

### ISSUE THREAD

**Issue by Yunme** [shadowsocks/shadowsocks-iOS#235]
同一个在Android手机和Windows上都能用，但在Mac上就翻不出去。日志一直跳"Could not bind" 求解.

**Comment by llxxxll** [comment]
遇到同样的问题，至少有一个月了。

**Comment by llxxxll** [comment]
Encountered the same problem, has been a month

**Comment by Yunme** [comment]
问题解决了，原来是自己手贱用brew安装了shadowsocks-libev导致的，用brew把它卸载，重启就好了。

**Comment by jasoncfpl** [comment]
我也碰到这么问题了，但是我没有安装shadowsocks-libev啊

**Comment by hailiyouyu** [comment]
@cnexcelee  请问问题解决了吗，我是在公司一直"Could not bind"，在家没问题~

**Comment by llxxxll** [comment]
mac下重新初始化网络就可以用了，应该是一些设置导致的不能联网。

**Comment by maxwu** [comment]
@llxxxll , thanks, 请问做了哪个重新初始化? 我也发现同样的问题.

**Comment by tomnicos** [comment]
程序高级设置里面的本地socks5监听地址不对导致的，改回127.0.0.1就好了
