### ISSUE TITLE
Mac OS无法使用PAC

### ISSUE THREAD

**Issue by Mac0ne16** [shadowsocks/shadowsocks-iOS#236]
macOS Sierra Safari只能通过全局才能正常访问，PAC工作不正常！

**Comment by ynhzzu** [comment]
我发现是file:///.../gfwlist.js在新版safari上无法使用，所以我安装了一个nginx，把pac文件放到nginx目录中，用http://.../gfwlist.js可以正常使用了。

**Comment by nanacheung** [comment]
我的也是有问题！用的showdowsocks X版本完全连不上，NG版本的就只能连接chrome，Safari要全局是才能连上！😭😭

**Comment by Mac0ne16** [comment]
新版本的客户端问题解决了https://github.com/qinyuhang/ShadowsocksX-NG/releases

**Comment by szmichaelyb** [comment]
现在确实好些了。。。
