### ISSUE TITLE
mac 下无法连接，服务器没问题

### ISSUE THREAD

**Issue by jasoncfpl** [shadowsocks/shadowsocks-iOS#240]
日志：
16/9/18 10:18:47.631 ShadowsocksX[3287]: pac proxy set to auto
16/9/18 10:18:53.963 ShadowsocksX[3287]: Connecting clients4.google.com
16/9/18 10:18:54.316 ShadowsocksX[3287]: Connecting clients4.google.com
16/9/18 10:18:54.670 ShadowsocksX[3287]: Connecting clients4.google.com
16/9/18 10:19:06.077 ShadowsocksX[3287]: Connecting fonts.googleapis.com
16/9/18 10:19:06.077 ShadowsocksX[3287]: Connecting fonts.googleapis.com
16/9/18 10:19:06.078 ShadowsocksX[3287]: Connecting www.google-analytics.com
16/9/18 10:19:06.427 ShadowsocksX[3287]: Connecting fonts.googleapis.com
16/9/18 10:19:06.427 ShadowsocksX[3287]: Connecting fonts.googleapis.com

**Comment by jasoncfpl** [comment]
搞定了

**Comment by renmoqiqi** [comment]
怎么搞定的
