### ISSUE TITLE
请问下你们的Intellij Idea是怎么设置走shadowsoscks代理的？

### ISSUE THREAD

**Issue by Yggdrasilqh** [shadowsocks/shadowsocks-iOS#246]
我照网上方法在http proxy里设了socks 127.0.0.1 1080还是没用啊，maven和gradle还是那么慢

**Comment by cjahv** [comment]
我用的Proxifier软件

**Comment by DrawBlack** [comment]
我也是这个问题，Java中使用代理访问不了国外网站

**Comment by xwsg** [comment]
这个问题你们解决了么？同求。

**Comment by vipzrx** [comment]
在 |idea.exe.vmoptions| 及 |idea64.exe.vmoptions| 中追加

|-DproxySet=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=1080 |

127.0.0.1为HTTP代理服务器地址

1080为HTTP代理服务器端口


好用射U

**Comment by huahuayu** [comment]
网上查到的我都配置了，不好使

**Comment by Tiakon** [comment]
https://www.jianshu.com/p/a0ec13a34a4b 亲测有效

**Comment by Tiakon** [comment]
![image](https://user-images.githubusercontent.com/21116907/46926350-f9231b00-d062-11e8-9eff-abcd2a85bb26.png) 替换上一步中的 url 即可

**Comment by inused** [comment]
maven的代理是在它自己的配置文件中设置的

**Comment by MrFL** [comment]
> https://www.jianshu.com/p/a0ec13a34a4b 亲测有效

页面挂掉了

**Comment by terwer** [comment]
https://www.cnblogs.com/uniquezhangqi/p/9199281.html 可以使用

**Comment by sanwancoder** [comment]
shadowsocks如何进行设置呢？

我设置127.0.0.1发现确实不行

**Comment by sanwancoder** [comment]
> ![image](https://user-images.githubusercontent.com/21116907/46926350-f9231b00-d062-11e8-9eff-abcd2a85bb26.png) 替换上一步中的 url 即可

找不到复制本地PAC地址图标呢 请问如何解决

**Comment by oldthreefeng** [comment]
> > ![image](https://user-images.githubusercontent.com/21116907/46926350-f9231b00-d062-11e8-9eff-abcd2a85bb26.png) 替换上一步中的 url 即可
> 
> 找不到复制本地PAC地址图标呢 请问如何解决

打开`Appearance & Behavior`> `System Settings` > `Http Proxy`
点选 `Auto-detect proxy settings` > `Automatic proxy configuration URL`

复制pac地址到这个url里面即可。@huahuayu 
完美解决idea走ss代理，跪谢大佬@sanwancoder  @Tiakon

**Comment by H0o0K** [comment]
ss开全局模式，idea  no proxy就可以了

**Comment by ghost** [comment]
1. 在idea中选择HTTP代理(**测试可用**)
在我的ssr设置中可以看到HTTP代理端口, 每个人的ssr客户端不同,这个端口可能不一样,自行查看,将这个端口填入idea中
![DeepinScreenshot_select-area_20191012113817](https://user-images.githubusercontent.com/52375886/66694360-14138400-ece5-11e9-84d0-2cdfb6328e72.png)
![DeepinScreenshot_select-area_20191012113747](https://user-images.githubusercontent.com/52375886/66694340-e8909980-ece4-11e9-848e-cfc4f868ed68.png)
2. 在idea中选择SOCKS (**测试不可用,原因未知**)
> 我的也不能上网,怀疑可能idea用的是socks4
```
分析: 在chrome的SwitchyOmega中设置代理协议为SOCKS5, 网络没问题, 设置为SCOKS4的时候, 网络就连不上.
```
![DeepinScreenshot_select-area_20191012114803](https://user-images.githubusercontent.com/52375886/66694465-31951d80-ece6-11e9-9cf6-8c41b7f3d735.png)

**Comment by qq253498229** [comment]
shadowsocks开http代理，然后在idea里面设置http proxy。
或者直接用proxifier全局代理。

**Comment by friedwm** [comment]
初学Android Studio，折腾半天发现是不支持socks代理，改成http代理即可。注意端口号要设置成你ssr的端口，位置在：选项设置-本地端口，这个端口同时支持http和socks5

**Comment by huahuayu** [comment]
没想到这个issue这么多人感兴趣，我写了篇文章介绍
[Mac下terminal终端、jetbrains系列IDE如何科学上网](https://liushiming.cn/2020/04/28/mac-terminal-proxy-though-shadowsocks-pass-gfw/)  

[Mac下虚拟机如何使用主机的shadowsockets科学上网](https://liushiming.cn/2020/04/29/mac-virtual-machine-proxy-through-host-machine-shadowsocks/)

以上是最佳办法，不管你用命令行开发、还是jetbrains系列ide甚至在虚拟机开发，都可以完美解决了

**Comment by qtw1998** [comment]
> 没想到这个issue这么多人感兴趣，我写了篇文章介绍
> [Mac下terminal终端、jetbrains系列IDE如何科学上网](https://liushiming.cn/2020/04/28/mac-terminal-proxy-though-shadowsocks-pass-gfw/)
> 
> [Mac下虚拟机如何使用主机的shadowsockets科学上网](https://liushiming.cn/2020/04/29/mac-virtual-machine-proxy-through-host-machine-shadowsocks/)
> 
> 以上是最佳办法，不管你用命令行开发、还是jetbrains系列ide甚至在虚拟机开发，都可以完美解决了

感谢巨佬！！

**Comment by yangbailiang** [comment]
在你的idea代理里面，配置你代理软件的ip（127.0.0.1）端口（本地监听端口）及协议就行了，比如我用的v2ray，在设置->参数设置里可以看到相关信息

**Comment by lagrange-doggy** [comment]
请问可以不必开启小火箭，单独让idea走代理吗？应该怎么设置。
我的只要开启小火箭，所有软件都是走代理的，但是每次都需要开启软件，懒得打开

**Comment by Liers** [comment]
> https://www.cnblogs.com/uniquezhangqi/p/9199281.html 可以使用
有用

**Comment by Saigut** [comment]
> https://www.cnblogs.com/uniquezhangqi/p/9199281.html 可以使用

有效。解决了 intellij CLion git 连不上 github 的问题。之前用 `Manual proxy configuration` 还以为是 CLion 全局代理呢，结果没啥效果。`Automatic proxy configuration URL` 自动代理就正常，不懂 intellij 这是啥逻辑。

**Comment by MarshuMax** [comment]
For me it works fine!
By the way, clash is the same, we just get port at clash main interface, and put the port number in the idea configure.
![image](https://user-images.githubusercontent.com/44150775/222869510-061573c7-1624-4bb1-896b-37dc4d26f9f8.png)
