### ISSUE TITLE
配置不生效，在最新的macos 10.12.2 (16C67)中配置完了服务器。

### ISSUE THREAD

**Issue by kylezhang** [shadowsocks/shadowsocks-iOS#252]
#### 在最新的macos 10.12.2 (16C67)中配置完了服务器，确定后，然后再次打开后要使用设定好的服务器时，结果啥都没有，和刚下载安装的一样，不知道咋回事儿，我air和pro都是这样的。

**Comment by meritozh** [comment]
使用shadowsocksX-NG作为macOS平台下的shadowsocks客户端，应该不会有问题

**Comment by Huangjiaqi0421** [comment]
我mac os10.12.1（16B2659）安装的dmg的包，打不开

**Comment by qiuyuzhou** [comment]
@S-MILE-S 这边项目已经没人维护了
