### ISSUE TITLE
-bash: ssserver: command not found

### ISSUE THREAD

**Issue by nlpjoe** [shadowsocks/shadowsocks-iOS#253]
[https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File](https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File)
It seems that `ssserver -c /etc/shadowsocks.json` doesn't work and I can't find a way to solute it.

**Comment by qiuyuzhou** [comment]
@BiggerGao Hi, you comment at wrong place.
