### ISSUE TITLE
Mac10.12.2终端代理127.0.0.1:1080端口无效

### ISSUE THREAD

**Issue by mydaoyuan** [shadowsocks/shadowsocks-iOS#254]
export http_proxy="http://127.0.0.1:1080"
export https_proxy="http://127.0.0.1:1080"
终端使用了代理以后，curl ip.cn就卡死了，没连接，实在没办法解决了

**Comment by codeshold** [comment]
终端开启的是http代理？ 不是socket5代理？

**Comment by mydaoyuan** [comment]
https://github.com/shadowsocks/shadowsocks-iOS/wiki/Shadowsocks-for-OSX-%E5%B8%AE%E5%8A%A9
文档说明里面是说用的PAD代理，关闭以后会用socket5代理运行在127.0.0.1:1080 上，但是我关闭以后也没用

**Comment by mydaoyuan** [comment]
我用chrome的proxy switchysharp插件可以代理127.0.0.1:1080端口的，正常上网

**Comment by codeshold** [comment]
你终端设置的是http/https代理，然而shadowsocks提供的是socks代理，终端要设置为使用socks5代理（而不是http/https
proxy)

2017-01-22 10:35 GMT+08:00 唐道远 <notifications@github.com>:

**Comment by mydaoyuan** [comment]
好的，我设置一下，谢谢了

**Comment by mydaoyuan** [comment]
抱歉，我使用了proxychains，配置文件里面写了socks5 127.0.0.1 1080 
```
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.12/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12/lib/libproxychains4.dylib
```
运行的时候也显示这个了，但是curl ip.cn显示的还是国内的地址，晕😲

**Comment by mydaoyuan** [comment]
使用了polipo解决了，proxychains因为os的安全机制无法工作

**Comment by mrdulin** [comment]
使用proxychains-ng，同样的问题，配置文件已配置ss的代理socks5 127.0.0.1 1080，但是

```bash
proxychains4 curl -i http://ip.cn
```
依旧显示国内ip。

-- update --

OSX系统升级后SIP的问题
