### ISSUE TITLE
建议大家使用这个版本  https://github.com/yangfeicheung/Shadowsocks-X/releases

### ISSUE THREAD

**Issue by yangfeicheung** [shadowsocks/shadowsocks-iOS#299]
no comment

**Comment by kunx-edu** [comment]
里面的免费试用节点不能修改，不能删除，让人很不爽，已经拆卸了

**Comment by yangfeicheung** [comment]
可以删除的，在编辑服务器那里直接删除就行了。。。。。

**Comment by yangfeicheung** [comment]
已经加入了高可用性模式，可以自动选择最优的服务器

**Comment by slow-is-fast** [comment]
测试了一下，不太好用，编辑服务器的时候不停提示要输入密码

**Comment by yangfeicheung** [comment]
@slow-is-fast 这个大概是因为您没有授权导致的，需要自动配置网络，只有在您授权之后，才不会要求，否则需要您手动配置网络

**Comment by weelin-zhang** [comment]
nice

**Comment by lidepeng701** [comment]
手机版的呢？

**Comment by yangfeicheung** [comment]
mac版本：

https://github.com/yangfeicheung/Shadowsocks-X/releases

手机版本：

https://itunes.apple.com/us/app/potatso-lite/id1239860606?mt=8

**Comment by Tsahao** [comment]
请问 shadowsocks X NG 说是 shadowsocks X 的下一代版本？为什么这个还在更新

**Comment by yangfeicheung** [comment]
@Tsahao  不同的人可以开发不同的版本的，不会互相影响，这个跟NG版本有些区别的

**Comment by xylinuxkernel** [comment]
请问这个iOS 怎么用了

**Comment by AgoniNemo** [comment]
@xylinuxkernel 可以用FirstWingy,这个是非官方的,不知道保险不保险

**Comment by chaplin8** [comment]
@AgoniNemo 你是说FirstWingy是非官方的不保险，还是楼上的不保险啊？

**Comment by yangfeicheung** [comment]
We have app store version, you can download from mac app store
https://itunes.apple.com/app/shadowsocks-x/id1295053131?ls=1&mt=8

and github version:
https://github.com/yangfeicheung/Shadowsocks-X

**Comment by AgoniNemo** [comment]
@chaplin8 我的意思是FirstWingy是非官方的，不保险，现在用的是SsrConnectPro，感觉还行，虽然也不是官方的
