### ISSUE TITLE
在自动代理模式下，如何让特定的网址走外网呢？

### ISSUE THREAD

**Issue by monty086** [shadowsocks/shadowsocks-iOS#306]
在自动代理模式下，如何让特定的网址走外网呢？
是不是要编辑自动模式下的PAC
还是要编辑GFWlist的用户规则
具体怎么编辑呢？
比如我想添加www.baidu.com这个网址在自动代理模式下，只要访问这个地址就走外网，如何编辑呢？

**Comment by monty086** [comment]
已找到原因

**Comment by Ryola** [comment]
请问是怎么解决的？如何让特定的网址走外网？

**Comment by Ryola** [comment]
> 已找到原因

请问是怎么就解决的？如何让特定的网址访问外网
