### ISSUE TITLE
.

### ISSUE THREAD

**Issue by MuYunyun** [shadowsocks/shadowsocks-iOS#333]

**Comment by wyxy2005** [comment]
山寨的，大家别点

**Comment by wyxy2005** [comment]
> 点击 [链接](http://jiasd.us/877)(这个 vpn 用了 3 年了，安利下), 进入软件下载&教程, 点击 ios 客户端下载。
> 
> 该教程亲测有效, 时间(2019.1.28)

卖vpn就卖，别挂羊头卖狗肉搞忽悠

**Comment by MuYunyun** [comment]
你点进去看教程试过了么? 没试过别瞎带节奏。有更好的教程你可以分享出来, issue 关了, 没意思。
