### ISSUE TITLE
Yosemite Public Beta Safari 自动模式失效

### ISSUE THREAD

**Issue by rainyzz** [shadowsocks/shadowsocks-iOS#42]
您好，我今天升级了 Yosemite Public Beta 1，使用 shadowsocksX 1.10

在自动代理模式下 Safari 无法访问国外网站，官方 Twitter 应用也不行，但是 Chrome 是可以的

在全局模式下所有浏览器和应用都是没问题的

**Comment by choubb** [comment]
删除pac file， 关开shadowsocks， 搞定。 MAC Pro

**Comment by alex1212112** [comment]
@clowwindy  您好，我想请教下，为什么在PAC 地址后面加上 ?t=123 就能强制 safari 刷新 pac呢？

**Comment by NotCoderJack** [comment]
@clowwindy 服！删掉gfwlist.js，关闭然后打开，好使！
