### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by leoleozhu** [shadowsocks/shadowsocks-iOS#57]
rev: d9a59fd

/Users/leo/Projects/shadowsocks-iOS/zxing-objc/ZXingObjC/client/result/ZXCalendarParsedResult.m:72:5: error: 
      use of undeclared identifier '_description'; did you mean 'description'?
    _description = description;
    ^~~~~~~~~~~~
    description
/Users/leo/Projects/shadowsocks-iOS/zxing-objc/ZXingObjC/client/result/ZXCalendarParsedResult.m:53:68: note: 
      'description' declared here
            attendees:(NSArray *)attendees description:(NSString *)descr...
                                                                   ^
1 error generated.

*\* BUILD FAILED **

The following build commands failed:
    CompileC build/ZXingObjC.build/Release-iphonesimulator/ZXingObjC-iOS.build/Objects-normal/i386/ZXCalendarParsedResult.o ZXingObjC/client/result/ZXCalendarParsedResult.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by ilovebamboo** [comment]
*\* BUILD FAILED **

The following build commands failed:
    CompileC build/ZXingObjC.build/Release-iphonesimulator/ZXingObjC-iOS.build/Objects-normal/i386/ZXCalendarParsedResult.o ZXingObjC/client/result/ZXCalendarParsedResult.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
