### ISSUE TITLE
监听端口的ip为0.0.0.0,应该改成127.0.0.1

### ISSUE THREAD

**Issue by s7v7nislands** [shadowsocks/shadowsocks-iOS#68]
监听端口的ip为0.0.0.0,应该改成127.0.0.1,这样貌似比较好.

**Comment by PeerXu** [comment]
请问监听地址可以选择配置吗? 有需要在MAC上监听0.0.0.0:1080

**Comment by menghuan758** [comment]
当8090端口被其他程序占用时无法使用改程序进行自动代理。全局代理没问题
