### ISSUE TITLE
能不能调整添加的服务器顺序

### ISSUE THREAD

**Issue by i0sdev** [shadowsocks/shadowsocks-iOS#78]
4，5个服务器，调整顺序的话需要重新删了重来。

说到这个，能不能实现这样的功能——可以设定默认服务器，其他的作为备选，默认服务器连不上或者速度低于一个下限，就去连下一个备选，以此类推。

**Comment by clowwindy** [comment]
谁有兴趣实现这个功能可以发个 pull request.

**Comment by kofj** [comment]
cow有这种简单的负载均衡功能~可惜会go不会oc.
