### ISSUE TITLE
Import and export configuration

### ISSUE THREAD

**Issue by izon90** [shadowsocks/shadowsocks-iOS#83]
希望开发者能够提供一个增加导入导出服务器列表的功能。

**Comment by clowwindy** [comment]
谁有兴趣实现这个功能可以发个 pull request.

**Comment by kairyou** [comment]
支持, 更新新版发现用update PAC from GFWLIST后, 自己增加的一些域名规则, 全部被替换掉了.  
建议: 
1. 在gfwlist.js, var rules = [..];前面增加一个var customRules = [];来设定默认rules里面没有的规则.
2. 或者增加custom.js 单独存放用户的规则.
这样可以避免升级后自定义规则被覆盖的问题. 
另外我觉得自定规则, 按["aaa":"1或0", "bbb":"1或0"], 来设定是否用这条规则是很不错的. 比如, 想把gfwlist里面的一条规则disable, 就可以设定"XXX":"0"; 而添加默认没有的, 就"XXX":"1".
