### ISSUE TITLE
Issue of sharing Mac Shadowsocks proxy to iPhone

### ISSUE THREAD

**Issue by xuyuanme** [shadowsocks/shadowsocks-iOS#87]
1. Run Shadowsocks client on Mac OS X 10.10.1, it works fine without issue
2. Set up Mac to share ethernet network as WiFi, host IP is 192.168.2.1
3. Connect iPhone (iOS 8.1) to the WiFi, and set proxy to http://192.168.2.1:8090/proxy.pac
4. The iPhone network connection (for example baidu.com) is ok, but all visit through proxy.pac (for example twitter.com) does not work. iPhone Chrome returns time out error (twitter.com can be visited on Mac Chrome).

**Comment by clowwindy** [comment]
We don't support Share over LAN yet.

**Comment by autosquid** [comment]
A solution is to set up another http proxy with, for example, polipo, and the allow connections with local network within the configuration file for polipo.
