### ISSUE TITLE
Add "Launch when start" feature for OS X 

### ISSUE THREAD

**Issue by mdluo** [shadowsocks/shadowsocks-iOS#88]
Add an option to decide whether shadowsocks will launch when OS X starts.

**Comment by clowwindy** [comment]
Sounds good. Please send a pull request if anybody want to implement this feature.

**Comment by mdluo** [comment]
Here's an alternative methods:
Add `ShadowsocksX` in System Preference > Users & Groups > Login Items

**Comment by xain** [comment]
It is much easier to use the function if there is a option in menu list.
