### ISSUE TITLE
2.6.2更新

### ISSUE THREAD

**Issue by i0sdev** [shadowsocks/shadowsocks-iOS#89]
1. 2.6.2的版本里是不是吧公共服务器取消了？
2. 能有自动更新功能吗？不然老是要手动下载。
3. 注意到新版的pac文件里有的域名前面有2竖线有的却没有，代表什么意思？
4. 更新log哪里可以看到？

**Comment by vicliu1990** [comment]
1、 我这边也没有公共服务器了

2、4 ， 支持

**Comment by clowwindy** [comment]
1. 维护不下去，去掉了。
2. 有安全风险，暂时不加任何能够遥控执行代码的功能。
3. https://code.google.com/p/autoproxy-gfwlist/wiki/Rules
4. 这个版本没有。iOS 版更新见 App Store。
