### ISSUE TITLE
osx 版的能加个版本号显示吗？

### ISSUE THREAD

**Issue by kikyous** [shadowsocks/shadowsocks-iOS#91]
都不知道现在用的是哪个版本的

**Comment by vicliu1990** [comment]
恩，版本号有必要

**Comment by clowwindy** [comment]
![screen shot 2015-01-23 at 17 24 51](https://cloud.githubusercontent.com/assets/1073082/5872289/ce224292-a324-11e4-946f-e0496198f2f0.png)
