### ISSUE TITLE
关于pac的几个小建议

### ISSUE THREAD

**Issue by vicliu1990** [shadowsocks/shadowsocks-iOS#92]
1、pac能否加个版本号 或者 时间。  可以查看本机pac的版本号或时间。

2、当GFWlist的pac有更新时，能否提示我？
小红点 或者 弹框

3、增加勾选项，自动更新pac

**Comment by clowwindy** [comment]
从增加这个功能到现在，用户们一个规则也没有向 GFWList 提交 ＝。＝
GFWList 不是凭空产生的，既然没有提交，GFWList 也不会更新。
你们只会要求，却一点也不愿贡献。那我还浪费时间做这个功能做啥。

**Comment by vicliu1990** [comment]
0 0，原来这样
