### ISSUE TITLE
有人编译的时候遇到过这个问题吗？

### ISSUE THREAD

**Issue by jShi-git** [shadowsocks/shadowsocks-iOS#93]
如下图所示，编译的时候提示文件缺失（sodium.h）

![-2](https://cloud.githubusercontent.com/assets/3771576/5876349/74a3dfc8-a351-11e4-9476-600394b91264.png)

**Comment by wangsijie** [comment]
同遇到，不知道这个sodium.h是什么东西

**Comment by wangsijie** [comment]
解决了，需要安装libsodium（http://doc.libsodium.org/installation/README.html）
安装完后在xcode路径加入/usr/local
这个应该可以关闭啦

**Comment by jShi-git** [comment]
@wangsijie 我刚刚装了下这个库，好像还是不行，方便截个xcode里面配置的图吗？
我的配置如下：
![-2](https://cloud.githubusercontent.com/assets/3771576/5886517/2f2996f8-a3de-11e4-9c79-b92668f8abfe.png)
![-3](https://cloud.githubusercontent.com/assets/3771576/5886518/346ffe22-a3de-11e4-900c-b425e8607b80.png)

**Comment by jShi-git** [comment]
@wangsijie 好了，下了一个libsodium-ios，可以用

**Comment by wangsijie** [comment]
@jShi-git 我在iMac上发现装了libsodium竟然也不行，libsodium-ios你是怎么用的？我直接复制到shadowsocks-ios目录下，然后把dist/armv7/include路径加进来，编译出错了，想问问你是如何使用这个的。

**Comment by jShi-git** [comment]
@wangsijie 我完全换成cocoapod安装的，可以编译安装，不过没有翻墙效果
下面几个库用的cocoapod
platform :ios, '7.0'
pod "GCDWebServer"
pod "AFNetworking"
pod "Masonry"
pod "libsodium"

**Comment by scorfishyu** [comment]
@jShi-git 我链接了libsodium-ios这个库还是有链接错误
Undefined symbols for architecture armv7:
  "_crypto_stream_salsa20_xor_ic", referenced from:
      _cipher_update in libshadowsocks.a(encrypt.o)
  "_crypto_stream_chacha20_xor_ic", referenced from:
      _cipher_update in libshadowsocks.a(encrypt.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by WangWenchao** [comment]
同样的编译时遇到这个问题

**Comment by alanhe421** [comment]
好麻烦，，，，
