### ISSUE TITLE
[iOS]Global proxy doesn't take effect

### ISSUE THREAD

**Issue by zeruniverse** [shadowsocks/shadowsocks-iOS#94]
After I choose global proxy in setting, I still get my iPhone's IP in www.ip.cn

[iPhone 6 with shadowsocks downloaded from app store]

**Comment by wangsijie** [comment]
@zeruniverse You should restart your Shadowsocks App after changing the proxy mode.

**Comment by zeruniverse** [comment]
Yes, I restarted before testing. Seems that when you choose global proxy, shadowsocks will use proxy server for sites not in China, however, for sites in China, it just try to access directly.

**Comment by wangsijie** [comment]
@zeruniverse I retried for several times and find out that you are right.
