### ISSUE TITLE
Why not use cocoapods?

### ISSUE THREAD

**Issue by Julyyq** [shadowsocks/shadowsocks-iOS#99]
Git submodule is difficult to manage dependences, why not use [cocoapods](http://cocoapods.org/)?

**Comment by clowwindy** [comment]
The code of every 3rd party project is modified.

**Comment by Julyyq** [comment]
@clowwindy Alright, there's another choice [Carthage](https://github.com/Carthage/Carthage) for this specific situation, I think the package manager tool is the best way instead git submodule. Just think about my advice, thank you.
